services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  cliente-service:
    build: ./cliente-service
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq

  cuenta-service:
    build: ./cuenta-service
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
